# upload_kids_youtube.py
# Uploads to HerooQuest YouTube Kids channel (YOUTUBE_CREDENTIALS_KIDS secret)
# v2.1 FIXES:
#   - Thumbnail upload wrapped in try/except with clear message
#   - Broader scene image search (glob + specific paths)
#   - Better summary output with Short ID saved to meta
#   - Thumbnail 403 = channel not verified — clear instructions printed
import os
import json
from pathlib import Path
from datetime import date
from googleapiclient.discovery import build
from googleapiclient.http import MediaFileUpload
from google.oauth2.credentials import Credentials

TODAY     = date.today().isoformat()
META_PATH = Path(f"output/kids_meta_{TODAY}.json")
meta      = json.loads(META_PATH.read_text())

creds_json = json.loads(os.environ["YOUTUBE_CREDENTIALS_KIDS"])
creds      = Credentials.from_authorized_user_info(creds_json)
youtube    = build("youtube", "v3", credentials=creds)


# ── Find thumbnail image ──────────────────────────────────────────────────────
# Looks for scene images generated by generate_kids_video.py
# Tries specific names first, then broad glob search
def find_thumbnail() -> Path | None:
    candidates = (
        [
            Path("output/kids_scene_01.png"),
            Path("output/kids_scene_02.png"),
            Path("output/kids_scene_03.png"),
        ]
        + sorted(Path("output").glob("kids_scene_*.png"))
        + sorted(Path("output").glob("kids_*.png"))
    )
    for p in candidates:
        if p.exists() and p.stat().st_size > 1000:  # ignore empty/tiny files
            return p
    return None


def upload_thumbnail(video_id: str, label: str) -> bool:
    """
    Upload custom thumbnail for a video.
    Returns True on success, False on failure.
    403 error = channel not verified for custom thumbnails.
    Fix: YouTube Studio → Settings → Channel → Feature eligibility → Verify
    """
    thumb = find_thumbnail()
    if not thumb:
        print(f"[YT-KIDS] ⚠️ No scene image found for {label} thumbnail")
        print("          Expected: output/kids_scene_01.png")
        print("          Check generate_kids_video.py saves scene images to output/")
        return False
    try:
        youtube.thumbnails().set(
            videoId=video_id,
            media_body=MediaFileUpload(str(thumb), mimetype="image/png")
        ).execute()
        print(f"[YT-KIDS] ✅ Thumbnail uploaded for {label}: {thumb.name}")
        return True
    except Exception as e:
        err_str = str(e)
        if "403" in err_str or "forbidden" in err_str.lower():
            print(f"[YT-KIDS] ⚠️ Thumbnail upload requires channel verification.")
            print("          Fix (one time, 5 minutes):")
            print("          1. Go to https://studio.youtube.com → HerooQuest channel")
            print("          2. Settings → Channel → Feature eligibility")
            print("          3. Click Verify → enter phone number → SMS code")
            print("          4. Done — thumbnails will work from next upload")
        else:
            print(f"[YT-KIDS] ⚠️ Thumbnail upload failed: {e}")
        return False


# ── Upload full video ─────────────────────────────────────────────────────────
print("[YT-KIDS] Uploading full video...")
body = {
    "snippet": {
        "title": meta["title_en"][:100],
        "description": (
            f"{meta['description_en']}\n\n"
            f"Hindi: {meta['title_hi']}\n\n"
            f"Moral: {meta['moral_en']}\n\n"
            "#KidsStories #AnimatedStories #PixarStyle #ChildrenEducation "
            "#KidsCartoon #HindiKahani #KidsEnglish #MoralStories #HerooQuest"
        ),
        "tags":                meta["seo_tags"][:30],
        "categoryId":          "27",    # Education — gets into YouTube Kids
        "defaultLanguage":     "en",
        "defaultAudioLanguage":"en",
    },
    "status": {
        "privacyStatus":           "public",
        "selfDeclaredMadeForKids": True,   # CRITICAL — gets into YouTube Kids
        "madeForKids":             True,
    }
}
media    = MediaFileUpload(meta["video_path"], resumable=True, chunksize=10*1024*1024)
response = youtube.videos().insert(part="snippet,status", body=body, media_body=media).execute()

video_id = response["id"]
meta["youtube_video_id"]  = video_id
meta["youtube_video_url"] = f"https://www.youtube.com/watch?v={video_id}"
meta["public_video_url"]  = meta["youtube_video_url"]
META_PATH.write_text(json.dumps(meta, ensure_ascii=False, indent=2))
print(f"[YT-KIDS] ✅ Uploaded: https://youtu.be/{video_id}")

# Upload thumbnail for full video
upload_thumbnail(video_id, "full video")

# ── Upload short (9:16) ───────────────────────────────────────────────────────
print("[YT-KIDS] Uploading short...")
short_body = {
    "snippet": {
        "title":       f"#{meta['title_en'][:80]} #Shorts #KidsStories",
        "description": meta["description_en"],
        "tags":        (meta["seo_tags"] + ["Shorts"])[:30],
        "categoryId":  "27",
    },
    "status": {
        "privacyStatus":           "public",
        "selfDeclaredMadeForKids": True,
        "madeForKids":             True,
    }
}
short_media = MediaFileUpload(meta["short_path"], resumable=True)
short_resp  = youtube.videos().insert(
    part="snippet,status", body=short_body, media_body=short_media
).execute()
short_id = short_resp["id"]

# Save short ID to meta
meta["youtube_short_id"]  = short_id
meta["youtube_short_url"] = f"https://www.youtube.com/shorts/{short_id}"
META_PATH.write_text(json.dumps(meta, ensure_ascii=False, indent=2))
print(f"[YT-KIDS] ✅ Short uploaded: https://youtu.be/{short_id}")

# Upload thumbnail for short
upload_thumbnail(short_id, "short")

# ── Final summary ─────────────────────────────────────────────────────────────
print(f"\n[YT-KIDS] 🎉 Done!")
print(f"  Full video : https://youtu.be/{video_id}")
print(f"  Short      : https://youtu.be/{short_id}")
