import os
import json
import datetime
from pathlib import Path
import google.auth
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError
from googleapiclient.http import MediaFileUpload
from google.oauth2.credentials import Credentials

# ─── CONFIG ───────────────────────────────────────────────────────────────────
# Ensure these match your Google Cloud Console / GitHub Secrets
CLIENT_SECRET_FILE = 'client_secrets.json'
API_NAME = 'youtube'
API_VERSION = 'v3'
SCOPES = ['https://www.googleapis.com/auth/youtube.upload']

def get_service():
    """Authenticates and returns the YouTube service."""
    # This assumes you have your token/credentials handled via environment or file
    # For GitHub Actions, you usually use a stored Refresh Token
    creds = None
    if os.path.exists('token.json'):
        creds = Credentials.from_authorized_user_file('token.json', SCOPES)
    
    if not creds or not creds.valid:
        print("❌ Authentication Error: token.json is missing or invalid.")
        return None

    return build(API_NAME, API_VERSION, credentials=creds)

def upload_video(video_path, title, description):
    """Handles the actual YouTube API upload."""
    youtube = get_service()
    if not youtube:
        return

    body = {
        'snippet': {
            'title': title,
            'description': description,
            'tags': ['AI360Trading', 'Zeno', 'AlgorithmicTrading', 'Shorts'],
            'categoryId': '27' # Education
        },
        'status': {
            'privacyStatus': 'public', # Change to 'private' or 'unlisted' for testing
            'selfDeclaredMadeForKids': False,
        }
    }

    media = MediaFileUpload(
        str(video_path),
        mimetype='video/mp4',
        resumable=True
    )

    print(f"🚀 Uploading to YouTube: {title}...")
    request = youtube.videos().insert(
        part='snippet,status',
        body=body,
        media_body=media
    )

    response = None
    while response is None:
        status, response = request.next_chunk()
        if status:
            print(f"Uploaded {int(status.progress() * 100)}%")

    print(f"✅ Video Uploaded! Video ID: {response['id']}")
    return response

# ─── MAIN ENGINE (FIXED) ──────────────────────────────────────────────────────
def main():
    # 1. Setup Time and Paths
    today = datetime.datetime.now().strftime("%Y%m%d")
    output_dir = Path("output")
    meta_path = output_dir / f"meta_{today}.json"
    video_path = output_dir / f"reel_{today}.mp4"

    print(f"📅 Production Date: {today}")

    # 2. Critical Check: Does the video exist?
    if not video_path.exists():
        print(f"❌ ERROR: Video file not found: {video_path}")
        print("Ensure 'generate_reel.py' finished successfully.")
        return

    # 3. Load Metadata (The fix for Line 183 FileNotFoundError)
    if meta_path.exists():
        try:
            with open(meta_path, "r", encoding="utf-8") as f:
                meta = json.load(f)
            
            # Extract info from the JSON generated by the Reel script
            title = meta.get("title", f"ZENO Daily Wisdom {today}")
            description = meta.get("description", "Daily market insights by AI360 ZENO.")
            print(f"📝 Metadata loaded successfully from {meta_path}")
        except Exception as e:
            print(f"⚠️ Error reading JSON: {e}. Using defaults.")
            title = f"AI360 ZENO Update - {today}"
            description = "Daily automated trading wisdom."
    else:
        # This prevents the script from crashing if the JSON is missing
        print(f"⚠️ Metadata file {meta_path} NOT FOUND. Using fallback title.")
        title = f"AI360 ZENO Trading Wisdom - {today} #Shorts"
        description = "Daily market updates and motivation. #AI360Trading #Zeno"

    # 4. Execute Upload
    try:
        upload_video(video_path, title, description)
    except HttpError as e:
        print(f"❌ An HTTP error occurred: {e.resp.status} - {e.content}")
    except Exception as e:
        print(f"❌ An unexpected error occurred: {e}")

if __name__ == "__main__":
    main()
