"""
upload_youtube.py — AI360Trading
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Uploads reels to YouTube. Handles two reel types:
  --type morning  → morning_reel_YYYYMMDD.mp4
  --type reel     → reel_YYYYMMDD.mp4 (ZENO evening reel)

v2.3 (2026-05-31):
  FIX — Stop skipping the custom thumbnail for Shorts.
    Old code skipped thumbnails().set() for reel/morning/short on the
    assumption Shorts thumbnails were unsupported via API. A custom thumbnail
    still drives CTR on Search / channel Shorts grid / Browse / shared links,
    so we now always attempt it (fail-open — never breaks the upload).

v2.2 FIXES (May 2026):

FIX 1 — Custom thumbnail upload for all reel types
  Morning reel: No thumbnail was being set → YouTube auto-picks a frame
  ZENO reel: generate_reel.py v2.1 builds thumbnail but upload was NOT setting it
  Fix: After upload → thumbnails().set() using thumb_path from meta

FIX 2 — Thumbnail design principle (from competitor analysis)
  What works: Image + readable text that makes viewer STOP and READ in feed
  Morning reel: ZENO + "MORNING BRIEF" + sentiment (BULLISH/BEARISH) + Nifty level
                Viewer reads "NIFTY 23250 BULLISH" in feed → curious → clicks
  ZENO reel:   ZENO + "PATIENCE IS KEY" + today's lesson → readable in 2 seconds

  This increases:
  - CTR (people click because they can read the value proposition)
  - Watch time (already engaged from reading thumbnail)
  - Subscriber conversion (they feel informed even from thumbnail)

FIX 3 — Thumbnail generator added directly here
  If meta has thumb_path → use it (generated by reel scripts)
  If meta has no thumb_path → generate one here as fallback
  Fallback: ZENO + big text + sentiment colour

Last updated: May 2026
"""

import os
import sys
import json
import argparse
import re
import textwrap
import datetime
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont
from google.oauth2.credentials import Credentials
from googleapiclient.discovery import build
from googleapiclient.http import MediaFileUpload

CONTENT_MODE = os.environ.get("CONTENT_MODE", "market").lower()
OUTPUT_DIR   = Path("output")
IMAGE_DIR    = Path("public/image")

FONT_BOLD = [
    "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",
    "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf",
    "/usr/share/fonts/truetype/ubuntu/Ubuntu-B.ttf",
]
FONT_REG = [
    "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
    "/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf",
]

def get_font(paths, size):
    for p in paths:
        if os.path.exists(p):
            try: return ImageFont.truetype(p, size)
            except: continue
    return ImageFont.load_default()

def lerp(c1, c2, t):
    return tuple(int(c1[i]+(c2[i]-c1[i])*t) for i in range(3))


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("--type", choices=["morning","reel"], default="reel")
    return parser.parse_args()


def resolve_files(reel_type: str):
    today = datetime.datetime.now().strftime("%Y%m%d")
    if reel_type == "morning":
        vpat = [f"morning_reel_{today}.mp4", "morning_reel_*.mp4"]
        mpat = [f"morning_reel_meta_{today}.json", "morning_reel_meta_*.json"]
    else:
        vpat = [f"reel_{today}.mp4", "final_zeno_reel.mp4", "reel_*.mp4"]
        mpat = [f"meta_{today}.json", "meta_*.json"]

    video_path = None
    for pat in vpat:
        cands = sorted(OUTPUT_DIR.glob(pat), key=os.path.getmtime, reverse=True)
        if cands: video_path = cands[0]; break

    meta_path = None
    for pat in mpat:
        cands = sorted(OUTPUT_DIR.glob(pat), key=os.path.getmtime, reverse=True)
        if cands: meta_path = cands[0]; break

    return video_path, meta_path


def get_service():
    try:
        creds_json = os.environ.get("YOUTUBE_CREDENTIALS")
        if not creds_json and os.path.exists("token.json"):
            with open("token.json") as f: creds_json = f.read()
        if not creds_json:
            print("❌ YOUTUBE_CREDENTIALS not set")
            return None
        creds = Credentials.from_authorized_user_info(json.loads(creds_json))
        print("✅ YouTube authenticated")
        return build("youtube","v3",credentials=creds)
    except Exception as e:
        print(f"❌ YouTube auth error: {e}")
        return None


# ─── THUMBNAIL BUILDER (fallback if reel script did not build one) ─────────────

def build_fallback_thumbnail(reel_type: str, meta: dict) -> Path:
    """
    Build thumbnail when reel script did not generate one.
    Based on competitor analysis:
    - Viewer must be able to READ useful info from thumbnail without clicking
    - Large character + large bold text = stops scrolling
    """
    W, H   = 1080, 1920
    today  = datetime.datetime.now().strftime("%Y%m%d")

    # Get sentiment from meta
    sentiment = meta.get("sentiment", "NEUTRAL").upper()
    nifty     = meta.get("nifty_level", 0)
    title_txt = meta.get("title", "")

    # Accent colour based on sentiment
    if sentiment == "BULLISH":
        accent = (0, 210, 100)
        bg_top = (5, 20, 10)
        bg_bot = (10, 40, 20)
    elif sentiment == "BEARISH":
        accent = (220, 55, 55)
        bg_top = (25, 5, 5)
        bg_bot = (50, 10, 10)
    else:
        accent = (255, 200, 0)
        bg_top = (10, 15, 35)
        bg_bot = (20, 30, 70)

    img = Image.new("RGB", (W, H))
    px  = img.load()
    for y in range(H):
        c = lerp(bg_top, bg_bot, y/H)
        for x in range(W): px[x, y] = c

    draw = ImageDraw.Draw(img, "RGBA")
    draw.rectangle([(0,0),(W,14)],   fill=accent)
    draw.rectangle([(0,H-14),(W,H)], fill=accent)

    # ZENO character — right side
    zeno_file = {"BULLISH":"zeno_happy.png","BEARISH":"zeno_sad.png"}.get(sentiment,"zeno_thinking.png")
    for zp in [IMAGE_DIR/zeno_file, IMAGE_DIR/"zeno_thinking.png"]:
        if zp.exists():
            try:
                zeno   = Image.open(str(zp)).convert("RGBA")
                zeno_h = int(H * 0.65)
                zeno_w = int(zeno.width*(zeno_h/zeno.height))
                zeno   = zeno.resize((zeno_w,zeno_h),Image.LANCZOS)
                img.paste(zeno,(W-zeno_w-10,H-zeno_h-60),zeno)
            except: pass
            break

    draw = ImageDraw.Draw(img, "RGBA")

    f_main  = get_font(FONT_BOLD, 120)
    f_sub   = get_font(FONT_BOLD, 68)
    f_nifty = get_font(FONT_BOLD, 80)
    f_badge = get_font(FONT_BOLD, 42)
    f_brand = get_font(FONT_REG,  34)

    if reel_type == "morning":
        # Morning reel: Show "MORNING BRIEF" + sentiment + Nifty level
        # Like competitor showing "NIFTY 23250-18 MAY 2026" in big text
        line1 = "MORNING"
        line2 = "BRIEF"
        ty = 100
        for line in [line1, line2]:
            for dx,dy in [(-4,4),(4,-4),(-4,-4),(4,4)]:
                draw.text((80+dx,ty+dy),line,font=f_main,fill=(0,0,0,200),anchor="la")
            draw.text((80,ty),line,font=f_main,fill=(255,200,0),anchor="la")
            ty += 138

        # Sentiment badge (like competitor's colored header)
        sent_txt = {"BULLISH":"📈 BULLISH DAY","BEARISH":"📉 BEARISH DAY","NEUTRAL":"⚖️ NEUTRAL"}.get(sentiment,"⚖️ TODAY")
        draw.rounded_rectangle([(80,ty+10),(80+380,ty+88)],radius=14,fill=accent)
        draw.text((270,ty+49),sent_txt,font=f_sub,fill=(0,0,0) if sentiment=="BULLISH" else (255,255,255),anchor="mm")
        ty += 108

        # Nifty level (specific data = viewer stops to read)
        if nifty > 0:
            nifty_str = f"NIFTY {nifty:,}"
            for dx,dy in [(-3,3),(3,-3)]:
                draw.text((80+dx,ty+40+dy),nifty_str,font=f_nifty,fill=(0,0,0,180),anchor="la")
            draw.text((80,ty+40),nifty_str,font=f_nifty,fill=(255,255,255),anchor="la")

        # 7:00 AM badge
        draw.rounded_rectangle([(20,20),(260,76)],radius=14,fill=(255,200,0))
        draw.text((140,48),"☀️ 7:00 AM IST",font=f_badge,fill=(0,0,0),anchor="mm")

    else:
        # ZENO reel: Show topic title + lesson preview
        safe_title = re.sub(r'[\u0900-\u097F]+','',title_txt).strip().upper()
        if not safe_title:
            safe_title = "TRADING WISDOM"
        lines = textwrap.wrap(safe_title, width=10)
        ty = 100
        for line in lines[:3]:
            for dx,dy in [(-4,4),(4,-4)]:
                draw.text((80+dx,ty+dy),line,font=f_main,fill=(0,0,0,200),anchor="la")
            draw.text((80,ty),line,font=f_main,fill=(255,200,0),anchor="la")
            ty += 138

        # ZENO Ki Baat badge
        draw.rounded_rectangle([(20,20),(340,76)],radius=14,fill=(255,200,0))
        draw.text((180,48),"ZENO KI BAAT",font=f_badge,fill=(0,0,0),anchor="mm")

    # Date (like competitor showing date)
    date_str = datetime.datetime.now().strftime("%d %b %Y")
    draw.text((80,H-70),date_str,font=f_brand,fill=(*accent,200),anchor="la")
    draw.text((W//2,H-60),"AI360Trading.in",font=f_brand,fill=(200,220,255,200),anchor="mm")

    path = OUTPUT_DIR / f"reel_thumb_fallback_{today}_{reel_type}.png"
    img.save(str(path),quality=95)
    print(f"[THUMB] Fallback thumbnail: {path.name}")
    return path


# ─── THUMBNAIL UPLOAD ─────────────────────────────────────────────────────────

def upload_thumbnail(youtube, video_id: str, thumb_path: Path) -> bool:
    """Upload custom thumbnail to YouTube. This is essential for CTR."""
    if not thumb_path or not Path(thumb_path).exists():
        print(f"[THUMB] Not found: {thumb_path}")
        return False
    try:
        media = MediaFileUpload(str(thumb_path), mimetype="image/png", resumable=False)
        youtube.thumbnails().set(videoId=video_id, media_body=media).execute()
        print(f"  ✅ Custom thumbnail set for {video_id}")
        return True
    except Exception as e:
        print(f"  ⚠️ Thumbnail upload failed: {e}")
        return False


def build_fallback_metadata(reel_type: str, today: str):
    try:
        from human_touch import ht, seo
        tags = seo.get_video_tags(mode=CONTENT_MODE, is_short=True)
    except:
        tags = ["ai360trading","StockMarket","Nifty50","Investing","Shorts"]

    hashtag_str = " ".join([f"#{t}" for t in tags[:12]])
    if reel_type == "morning":
        title = f"🌅 Morning Trading Brief — ai360trading #{today[-4:]} #Shorts"
        desc  = (f"🌅 Morning market update\n\n🌍 India, USA, UK, Brazil & UAE\n"
                 f"🌐 https://ai360trading.in\n📱 https://t.me/ai360trading\n"
                 f"⚠️ Educational only.\n\n#ai360trading #MorningBrief {hashtag_str}")
    else:
        title = f"🎯 ZENO Ki Baat — Trading Wisdom #{today[-4:]} #Shorts"
        desc  = (f"🎯 Daily trading wisdom by ZENO\n\n🌍 India, USA, UK, Brazil & UAE\n"
                 f"🌐 https://ai360trading.in\n📱 https://t.me/ai360trading\n"
                 f"⚠️ Educational only.\n\n#ZenoKiBaat #ai360trading {hashtag_str}")
    return title, desc, tags


def upload_video(youtube, video_path: Path, title: str, description: str, tags: list, lang: str = "hi"):
    body = {
        # defaultAudioLanguage lets YouTube auto-generate + auto-translate
        # captions per viewer country (works even without our own .srt).
        "snippet": {"title":title[:100],"description":description,"tags":tags[:30],"categoryId":"27",
                    "defaultLanguage": lang, "defaultAudioLanguage": lang},
        "status":  {"privacyStatus":"public","selfDeclaredMadeForKids":False}
    }
    media = MediaFileUpload(str(video_path), mimetype="video/mp4", resumable=True)
    print(f"🚀 Uploading: {title[:70]}...")
    try:
        req  = youtube.videos().insert(part="snippet,status",body=body,media_body=media)
        resp = None
        while resp is None:
            status, resp = req.next_chunk()
            if status: print(f"  {int(status.progress()*100)}%")
        vid_id  = resp["id"]
        vid_url = f"https://youtube.com/shorts/{vid_id}"
        print(f"✅ YouTube upload success! ID: {vid_id}")
        print(f"   URL: {vid_url}")
        # Auto-post the channel's own top comment with the Telegram funnel.
        try:
            import money_funnel as _mf
            _mf.post_first_comment(youtube, vid_id, lang)
        except Exception:
            pass
        return vid_id, vid_url
    except Exception as e:
        print(f"❌ Upload failed: {e}")
        return None, None


def main():
    args      = parse_args()
    reel_type = args.type
    today     = datetime.datetime.now().strftime("%Y%m%d")

    print(f"\n{'='*55}")
    print(f" upload_youtube.py — TYPE: {reel_type.upper()} | MODE: {CONTENT_MODE.upper()}")
    print(f"{'='*55}")

    video_path, meta_path = resolve_files(reel_type)

    if not video_path or not video_path.exists():
        print(f"❌ No video file found for type '{reel_type}'"); sys.exit(1)
    print(f"🎥 Video file: {video_path.name}")

    # Load meta
    meta = {}
    if meta_path and meta_path.exists():
        try:
            meta = json.loads(meta_path.read_text())
            print(f"📄 Meta file: {meta_path.name}")
        except: pass

    # Get title/desc/tags from meta or fallback
    title = meta.get("title","")
    desc  = meta.get("description","")
    tags  = meta.get("tags",[])
    if not title:
        title, desc, tags = build_fallback_metadata(reel_type, today)
    if isinstance(tags, list) and len(tags) == 0:
        _, _, tags = build_fallback_metadata(reel_type, today)

    print(f"📝 Title: {title[:70]}...")
    print(f"🏷️  Tags ({len(tags)}): {', '.join(tags[:5])}...")

    youtube = get_service()
    if not youtube: sys.exit(1)

    # Upload video
    srt_lang = meta.get("srt_lang", "hi")
    video_id, video_url = upload_video(youtube, video_path, title, desc, tags, lang=srt_lang)
    if not video_id:
        print("❌ Upload failed"); sys.exit(1)

    # ── Set custom thumbnail (fail-open) ──────────────────────────────────────
    # In the in-feed Shorts player YouTube shows a video frame, but a custom
    # thumbnail still drives CTR on Search, the channel Shorts grid, Browse and
    # shared links (Telegram/WhatsApp/Facebook). So we always attempt it.
    # upload_thumbnail() is fail-open — if YouTube ignores/refuses it, the upload
    # is unaffected. (Was previously skipped for shorts on the old assumption it
    # was unsupported via API.)
    thumb_path = meta.get("thumb_path","")
    if thumb_path and Path(thumb_path).exists():
        print(f"[THUMB] Using meta thumbnail: {Path(thumb_path).name}")
        upload_thumbnail(youtube, video_id, Path(thumb_path))
    else:
        print("[THUMB] Building fallback thumbnail...")
        fb_thumb = build_fallback_thumbnail(reel_type, meta)
        upload_thumbnail(youtube, video_id, fb_thumb)

    # Subtitle track for YouTube auto-translate (fail-open; needs force-ssl scope)
    srt_path = meta.get("srt_path", "")
    if srt_path and Path(srt_path).exists():
        try:
            from subtitle_helper import upload_caption
            upload_caption(youtube, video_id, srt_path, srt_lang)
        except Exception as e:
            print(f"[CC] Caption upload skipped (fail-open): {e}")

    # Save meta
    meta["youtube_video_id"] = video_id
    meta["youtube_video_url"]= video_url
    if meta_path and meta_path.exists():
        try:
            meta_path.write_text(json.dumps(meta, indent=2, ensure_ascii=False))
        except: pass

    # Save video ID for Facebook upload to read
    (OUTPUT_DIR / "youtube_video_id.txt").write_text(video_id)

    print(f"\n{'='*55}")
    print(f" upload_youtube.py — SUCCESS")
    print(f"{'='*55}")


if __name__ == "__main__":
    main()
